DEBUG:root:[2020-02-11 22:14:47 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:14:47 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
DEBUG:root:[2020-02-11 22:21:47 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:21:47 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
DEBUG:root:[2020-02-11 22:23:12 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:23:12 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
DEBUG:root:[2020-02-11 22:25:57 Eastern Standard Time] Type NameError Exception: name 'dirname' is not defined in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\hello.py at line 36.
DEBUG:root:[2020-02-11 22:26:34 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:26:34 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
DEBUG:root:[2020-02-11 22:28:08 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:28:08 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
DEBUG:root:[2020-02-11 22:30:32 Eastern Standard Time] Type OperationalError Exception: unable to open database file in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 335.
DEBUG:root:[2020-02-11 22:30:32 Eastern Standard Time] Type AttributeError Exception: 'NoneType' object has no attribute 'cursor' in c:\Users\Rob\source\repos\Basics\CodeTemplates\Python\hello\models\database_functions.py at line 134.
