DEBUG:root:[2020-01-20 12:37:15 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:10:50 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:11:34 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:12:09 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:15 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:36 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:13:42 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:14:28 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:15:47 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:20 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:41 Eastern Standard Time] Type ZeroDivisionError Exception: division by zero in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 28.
DEBUG:root:[2020-01-20 14:17:59 Eastern Standard Time] Type OperationalError Exception: no such table: Users in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\userdb_class.py at line 114.
DEBUG:root:[2020-01-20 14:17:59 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 30.
DEBUG:root:[2020-01-20 14:18:20 Eastern Standard Time] Type OperationalError Exception: no such table: Users in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\userdb_class.py at line 114.
DEBUG:root:[2020-01-20 14:18:20 Eastern Standard Time] Type TypeError Exception: 'NoneType' object is not iterable in c:\Users\Rob\source\repos\Basics\CodingTemplates\Python\hello.py at line 30.
